name: Prowe_Electronic_Store_FE CI/CD

on:
  push:
    branches:
      - homepage

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    # Clone code latest from homepage branch
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 16.x
          cache: npm

    - name: install dependencies
      run: npm ci

    - name: Set environment variable
      run: |
        REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
        echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> $GITHUB_ENV
        echo "::addmask::$REACT_APP_API_URL"
    - name: build
      run: npm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: install firebase
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
      # firebase login:ci on your local computer and store the token as the FIREBASE_TOKEN secret
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}