name: Prowe_Electronic_Store_FE CI/CD

on:
  push:
    branches:
      - homepage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: 16.x
          cache: npm

    - name: install dependencies
      run: npm ci

    - name: Print secret
      run: | 
        echo "API Key: ${{ env.REACT_APP_API_URL }}"

      # echo "Google Key: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"

    - name: build
      run: npm run build:prod
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }} 

    - name: install firebase
      run: npm install -g firebase-tools

    - name: login
      run: firebase login:ci --interactive --no-localhost

    - name: deploy
      run: firebase deploy --only hosting