name: Prowe_Electronic_Store_FE CI/CD

on:
  push:
    branches:
      - homepage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: install dependencies
      run: npm ci
    - name: Print secret
      run: | 
        echo "API Key: ${{ secrets.API_KEY }}"
    - name: build
      run: npm run-script build
    - name: login
      run: firebase login
    - name: deploy
      run: firebase deploy --only hosting